# Redirects
redirects:
  - /private-policy/ : /private-policy.html
  - /private-policy : /private-policy.html
  - /private-policy.html : /private-policy/
  - /private-policy.html* : /private-policy/$1/
